# Generated by Django 3.2.18 on 2023-05-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societyName', models.CharField(max_length=122)),
                ('memberName', models.CharField(max_length=122)),
                ('flatno', models.CharField(max_length=122)),
                ('openingBalance', models.IntegerField()),
                ('closingBalance', models.IntegerField()),
                ('date_add_member', models.DateField()),
            ],
        ),
    ]
