# Generated by Django 3.2.18 on 2023-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_societylist_societyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberslist',
            name='memberName',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
